# Generated by Django 2.1.5 on 2021-08-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Food', 'Food'), ('Household', 'Household'), ('Appliances', 'Appliances'), ('Electronics', 'Electronics'), ('Gaming', 'Gaming'), ('Computer Parts', 'Computer Parts')], max_length=200, null=True),
        ),
    ]
