# Generated by Django 2.1.5 on 2021-08-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_auto_20210813_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Future needs', 'Future needs'), ('Ordered', 'Ordered'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
                ('wishlist_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Wishlist')),
            ],
        ),
    ]
