# Generated by Django 2.1.5 on 2021-08-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210814_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Wishlist'),
        ),
    ]
