# Generated by Django 3.2.6 on 2021-08-21 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_auto_20210814_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Food', 'Food'), ('Clothing-Apparel', 'Clothing-Apparel'), ('Household', 'Household'), ('Appliances', 'Appliances'), ('Electronics', 'Electronics'), ('Gaming', 'Gaming'), ('Computer Parts', 'Computer Parts')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300, null=True)),
                ('account_type', models.CharField(choices=[('Company', 'Company'), ('Customer', 'Customer')], max_length=200, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
