# Generated by Django 3.2.6 on 2021-08-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210821_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='account_type',
        ),
        migrations.AddField(
            model_name='contactform',
            name='change_account_type',
            field=models.CharField(choices=[('Company', 'Company'), ('Customer', 'Customer'), ('No', 'No')], default='No', max_length=200),
        ),
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Being Reviewed', 'Being Reviewed'), ('Finished', 'Finished')], default='Sent', max_length=200),
        ),
    ]
