# Generated by Django 3.2.6 on 2021-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_contactform_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Ordered', 'Ordered'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], default='Pending Approval', max_length=200),
        ),
    ]
