# Generated by Django 3.2.6 on 2021-08-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_order_wishlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('Pre-Order', 'Pre-Order'), ('Available Now', 'Available Now')], max_length=200, null=True),
        ),
    ]
